spring:
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/ATHENA
    driver-class-name: org.mariadb.jdbc.Driver
    username: athena
    password: kjungjh5213#
